M48
; DRILL file {KiCad 8.0.2-8.0.2-0~ubuntu22.04.1} date 2024-06-09T18:07:19+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-09T18:07:19+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2-8.0.2-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X40.03Y-67.575
X40.03Y-72.425
T2
X37.0Y-67.275
X37.0Y-72.725
T3
X38.0Y-50.0
X38.5Y-91.0
X151.5Y-50.0
X151.5Y-91.0
M30
